apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "challengeapp.fullname" . }}
  labels:
    {{- include "challengeapp.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.availability.evictionStrategy.minAvailable }}
  selector:
    matchLabels:
      {{- include "challengeapp.selectorLabels" . | nindent 6 }}
