apiVersion: v1
kind: Secret
metadata:
  name: {{ include "challengeapp.fullname" . }}
  labels:
    {{- include "challengeapp.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ .Values.secrets.apiKey | required "You need to set an API_KEY! (--set secrets.apiKey=someValue)" | toString | b64enc | quote }}