{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "challengeapp.fullname" . }}
  labels:
    {{- include "challengeapp.labels" . | nindent 4 }}
{{- end }}
